version: "3.7"

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always

  example-python:
    image: example-python
    build: images/example-python
    command: ["./example.py"]
    volumes:
      - ./data:/data

  data-ingestion:
    image: data-ingestion
    build: images/data-ingestion
    command: ["./ingest.py"]
    volumes:
      - ./data:/data
    env_file:
      - .env

  data-pipeline:
    image: data-pipeline
    build: images/data-pipeline
    command: ["./pipeline.py"]
    volumes:
      - ./data:/data
    env_file:
      - .env